import "@/app/_styles/globals.css";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import ReactQueryProvider from "./_providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "پمو کافی",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="flex flex-col font-iransans">
        <ReactQueryProvider> {children}</ReactQueryProvider>

        <NextTopLoader color="#3b82f6" showSpinner={false} height={5} />
        <Toaster />
      </body>
    </html>
  );
}
