import type { Metadata } from "next";
import "@/app/_styles/globals.css";
import Header from "@/app/_components/Header";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="min-h-screen flex flex-col font-iransans">
        <Header />
        <div className="flex-1 px-8 py-12 grid">
          <main>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
